# Generated by Django 6.0.4 on 2026-04-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("sales_amount", models.IntegerField()),
                ("cost", models.IntegerField()),
            ],
        ),
    ]
